name: Feature request
description: Suggest a change to the package
title: '[Feature]: '
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the use case or limitation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: Describe the behavior or API you want.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example
      description: Add a code sample or mockup if it helps.
